### ISSUE TITLE
[error] [APNS] failed to connect gateway.sandbox.push.apple.com:2195, reason given: {:options, {:password, "..."}}

### ISSUE THREAD

**Issue by jeandavid** [chvanikoff/apns4ex#10] opened 2015-11-24 09:25 UTC
Hi! 
I am new to push notification, and quite frankly to elixir too. I was happy to find this library! But I run into an error in the very first step of using it. I hope you can help me figuring it out!

I have a valid certificate ck.pem (combined with my private key) and simple password "hello" -- I am able to connect with "openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert ck.pem"

I am setting this up in my phoenix project: 

config :apns,
  callback_module:    APNS.Callback,
  timeout:            30,
  feedback_interval:  1200,
  reconnect_after:    1000,
  support_old_ios:    true,
  pools: [
    myapp_dev_pool: [
      env: :dev,
      pool_size: 10,
      pool_max_overflow: 5,
      certfile: "ck.pem",
     cert_password: "hello"
    ]
  ]

Then I try to fire up phoenix.server, but I run into the above error: 
[error] [APNS] failed to connect gateway.sandbox.push.apple.com:2195, reason given: {:options, {:password, "hello"}}

What's happening? 
Thank you !!

**Comment by chvanikoff** [comment] 2015-11-24 10:25
Hi @jeandavid 
Please take a look at the same issue closed, I hope it will help: https://github.com/chvanikoff/apns4ex/issues/8

**Comment by jeandavid** [comment] 2015-11-24 11:01
Hey @chvanikoff, 

Somehow it only works when I remove any password to the certificate. Any further idea?

**Comment by chvanikoff** [comment] 2015-11-24 11:04
@jeandavid did u check the SO post mentioned in the issue? It didn't work for you?

**Comment by jeandavid** [comment] 2015-11-24 11:10
@chvanikoff yes. I generated my cert and key the same way as Ashish Chhabra does it in the SO article. I get the error above unless I do his third step (remove pass phrase) for the key.

**Comment by chvanikoff** [comment] 2015-11-24 11:12
@jeandavid that's weird. Ok I'll check it a bit later. I'm not using passphrase so can't reproduce the issue right now. Will ping u once done.

**Comment by adrienmo** [comment] 2015-12-30 11:00
@jeandavid The problem is that you are using binary string instead of a character list, the erlang ssl library only accept character list

cert_password: 'hello'

instead of

cert_password: "hello"

**Comment by zepplock** [comment] 2016-03-10 21:41
Closing this issue, fixed in https://github.com/adrienmo/apns4ex/commit/4579f036acaaa19dcd5830837468d40eae2fa96e

**Closed as completed** 2016-03-10 21:41 UTC
